version: '3'

services:

  user_microsservice:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - .:/ms_user
    env_file:
      - .env
      - .env.test

  user_postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - .docker/postgres:/data/postgres
    ports:
      - "5432:5432"