version: '3'

services:

  user_microsservice:
    build: .
    depends_on:
      - user_postgres
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - .:/ms_user
    env_file:
      - .env
      - .env.test

  user_postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - .docker/user/postgres:/data/postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - user_postgres
    env_file:
      - .env
    volumes:
      - .docker/pgadmin:/database/admin/pgadmin
    ports:
      - "5050:80"