broker:
  queue:
    email:
      name: ${EMAIL_BROKER_QUEUE_NAME:default.email}

spring:

  profiles:
    active: dev

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:ms_user}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASS:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}